### ISSUE TITLE
Настройка basename в BrowserRouter

### ISSUE THREAD

**Issue by avtopro** [AleksandrTatarenko/VIN-decoder#1]
GitHub Pages это хостинг с регистрозависимыми путями, поэтому начальная загрузка приложения по адресу https://aleksandrtatarenko.github.io/VIN-decoder/ работает, а после переходов внутри приложения адрес меняется на прописанный в basename "/vin-decoder" и после перезагрузки страницы мы получаем 404, например https://aleksandrtatarenko.github.io/vin-decoder/variables.

https://github.com/AleksandrTatarenko/VIN-decoder/blob/3c8bb615862e0aab0b308a43d7fe0d82d35cad18/src/index.js#L9-L11

Хорошо что basename указан, само по себе это правильно, только в качестве значения должен быть путь "/VIN-decoder".

**Comment by AleksandrTatarenko** [comment]
Ошибку понял, решил правильным поправить название репозитория, в нижнем регистре будет лучше.
