### ISSUE TITLE
Обработка HTML в описаниях переменных

### ISSUE THREAD

**Issue by avtopro** [AleksandrTatarenko/VIN-decoder#2]
В описаниях переменных есть HTML-разметка, которую нужно каким-то образом обрабатывать. Например, описание переменной 14 выглядит и выводится так: `<p>This is a numerical field to store the number of doors on a vehicle.</p>`.

Можно вычищать разметку, например через [sanitize-html](https://www.npmjs.com/package/sanitize-html), оставляя только текст, но в данном случае вполне уместно использовать метод React [dangerouslySetInnerHTML](https://ru.reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml) для преобразования разметки в соответствующие DOM-элементы.

https://github.com/AleksandrTatarenko/VIN-decoder/blob/3c8bb615862e0aab0b308a43d7fe0d82d35cad18/src/components/VariableItem/VariableItem.jsx#L4-L8

**Comment by AleksandrTatarenko** [comment]
Применил метод dangerouslySetInnerHTML в описании переменных в src/pages/variable/variable.jsx.
