### ISSUE TITLE
Загрузка данных для страницы Variable

### ISSUE THREAD

**Issue by avtopro** [AleksandrTatarenko/VIN-decoder#3]
Страница Variable получает данные о просматриваемой переменной из `location.state`. Поэтому пользователь обязан посетить страницу Variables со списком переменных прежде, чем переходить к Variable. Но если у веб-приложения есть какая-то публичная страница, то должна быть возможность этой страницей поделиться, а сейчас мы не можем увидеть информацию о переменной по прямой ссылке: https://aleksandrtatarenko.github.io/VIN-decoder/variables/14.

https://github.com/AleksandrTatarenko/VIN-decoder/blob/3c8bb615862e0aab0b308a43d7fe0d82d35cad18/src/pages/Variable/Variable.jsx#L30-L49

**Comment by AleksandrTatarenko** [comment]
Исправил данную ошибку, осуществляя поиск по id в полученном response getVariablesList.
